export const QUESTION_BANK = [
  {id:"history-start",category:"Our History",question:"When did Inclusive Health officially begin serving patients?",answers:["March 2024","March 2025","October 2025","January 2026"],correct:1,explanation:"Inclusive Health officially began serving patients in March 2025."},
  {id:"history-office",category:"Our History",question:"When did Inclusive Health begin welcoming patients at its Lynnwood office?",answers:["March 1, 2025","June 1, 2025","October 1, 2025","January 1, 2026"],correct:2,explanation:"The Lynnwood office opened to patients on October 1, 2025."},
  {id:"history-anniversary",category:"Our History",question:"What are we celebrating at the October 1, 2026 Open House?",answers:["Five years in practice","One year at the Lynnwood office","Ten years of telehealth","The opening of a hospital"],correct:1,explanation:"The Open House celebrates one full year in Inclusive Health's Lynnwood office."},
  {id:"history-independent",category:"Our History",question:"How did Inclusive Health begin?",answers:["As a national hospital chain","As an independently built community clinic","As a university medical center","As an insurance company"],correct:1,explanation:"Inclusive Health was independently built to create a more personal and inclusive healthcare experience."},
  {id:"mission-tagline",category:"Mission & Values",question:"What is Inclusive Health's official tagline?",answers:["Healthcare for Every Body","Care Without Compromise","A Better Class of Healthcare","Health Starts Here"],correct:2,explanation:"Inclusive Health's official tagline is “A Better Class of Healthcare.”"},
  {id:"mission-understanding",category:"Mission & Values",question:"Inclusive Health's philosophy begins with a belief in the power of what?",answers:["Technology","Understanding","Competition","Tradition"],correct:1,explanation:"Understanding is central to creating care that respects each person's needs, identity, and experience."},
  {id:"mission-actions",category:"Mission & Values",question:"Which actions best reflect Inclusive Health's mission?",answers:["Listen, value individuality, and support each health journey","Diagnose, prescribe, and discharge","Schedule, bill, and refer","Research, publish, and teach"],correct:0,explanation:"The mission emphasizes listening, valuing individuality, and supporting each person's health journey."},
  {id:"mission-welcome",category:"Mission & Values",question:"Who is welcome at Inclusive Health?",answers:["Only adults","Only LGBTQIA2S+ patients","People of all races, genders, orientations, sizes, and abilities","Only patients living in Lynnwood"],correct:2,explanation:"Inclusive Health is affirming and welcoming to people across identities, backgrounds, sizes, and abilities."},
  {id:"staff-founder",category:"Meet the Team",question:"Who founded Inclusive Health?",answers:["Tara Weidner","Dr. Joanne Thambuswamy","A regional hospital system","The Washington State Department of Health"],correct:1,explanation:"Inclusive Health was founded by Dr. Joanne Thambuswamy."},
  {id:"staff-physician",category:"Meet the Team",question:"What type of physician is Dr. Joanne Thambuswamy?",answers:["Cardiologist","Dermatologist","Board-certified family physician","Orthopedic surgeon"],correct:2,explanation:"Dr. Thambuswamy is a board-certified family physician."},
  {id:"staff-passion",category:"Meet the Team",question:"Which areas of care is Dr. Thambuswamy especially passionate about expanding?",answers:["Cosmetic surgery and sports medicine","Gender-affirming, reproductive, and HIV care","Emergency medicine and trauma surgery","Dental and vision care"],correct:1,explanation:"Her work especially emphasizes access to gender-affirming, reproductive, and HIV care."},
  {id:"staff-tara-role",category:"Meet the Team",question:"What is Tara Weidner's role at Inclusive Health?",answers:["Clinical Director","Laboratory Director","Hospital Administrator","Insurance Broker"],correct:0,explanation:"Tara is Inclusive Health's Clinical Director."},
  {id:"staff-tara-year",category:"Meet the Team",question:"In what year did Tara begin working in healthcare?",answers:["1995","2000","2010","2020"],correct:1,explanation:"Tara began working in healthcare in 2000."},
  {id:"staff-tara-start",category:"Meet the Team",question:"Which position launched Tara's healthcare career?",answers:["Physician assistant","Practice owner","Receptionist","Laboratory scientist"],correct:2,explanation:"Tara started in healthcare as a receptionist and built broad clinical and administrative experience from there."},
  {id:"staff-tara-specialties",category:"Meet the Team",question:"Which areas of medicine has Tara worked in?",answers:["Pediatrics","Internal medicine and rheumatology","Naturopathy","All of these"],correct:3,explanation:"Tara's experience includes pediatrics, internal medicine, rheumatology, and naturopathy."},
  {id:"location-city",category:"Location & Access",question:"In what Washington city is Inclusive Health's physical office located?",answers:["Everett","Seattle","Lynnwood","Bellevue"],correct:2,explanation:"Inclusive Health's physical office is located in Lynnwood, Washington."},
  {id:"location-address",category:"Location & Access",question:"Which address belongs to Inclusive Health?",answers:["19217 36th Avenue W, Suite 104","101 Inclusive Way, Suite 100","19217 Highway 99, Suite 1","425 Healthcare Avenue"],correct:0,explanation:"Inclusive Health is located at 19217 36th Avenue W, Suite 104, Lynnwood, WA 98036."},
  {id:"location-statewide",category:"Location & Access",question:"Do patients need to live near Lynnwood to receive care from Inclusive Health?",answers:["Yes, within five miles","Yes, within Snohomish County","No, care is available throughout Washington State","Only during the Open House"],correct:2,explanation:"Inclusive Health can serve patients throughout Washington State, including through virtual care."},
  {id:"location-appointments",category:"Location & Access",question:"Which appointment options does Inclusive Health offer?",answers:["Hospital visits and house calls only","In-person and virtual appointments","Virtual appointments only","Walk-in appointments only"],correct:1,explanation:"Patients can receive care through both in-person and virtual appointments."},
  {id:"location-land",category:"Location & Access",question:"Inclusive Health's Lynnwood office is located on the traditional lands of which peoples?",answers:["The Coast Salish peoples","The Seminole peoples","The Cherokee peoples","The Inuit peoples"],correct:0,explanation:"The Lynnwood area is on the traditional lands of Coast Salish peoples, including the Snohomish, Suquamish, Stillaguamish, and Tulalip Tribes."},
  {id:"services-four",category:"Care We Provide",question:"Which four major care areas are highlighted by Inclusive Health?",answers:["Family medicine, gender-affirming care, HIV care, and reproductive care","Dentistry, optometry, surgery, and physical therapy","Emergency medicine, radiology, oncology, and cardiology","Chiropractic care, podiatry, dermatology, and audiology"],correct:0,explanation:"Inclusive Health highlights family medicine, gender-affirming care, HIV care, and reproductive care."},
  {id:"services-ages",category:"Care We Provide",question:"Inclusive Health's family medicine services are available to whom?",answers:["Adults only","Children only","People of all ages","Existing members only"],correct:2,explanation:"Family medicine includes comprehensive primary care for people of all ages."},
  {id:"services-reproductive",category:"Care We Provide",question:"Which reproductive health services may be available through Inclusive Health?",answers:["Birth control, pregnancy care, and abortion care","Hospital deliveries only","C-sections and inpatient surgery","No reproductive healthcare"],correct:0,explanation:"Inclusive Health offers reproductive care that may include birth control, pregnancy care, and abortion care."},
  {id:"services-membership",category:"Care We Provide",question:"Why does Inclusive Health offer a membership option?",answers:["To replace every insurance plan","To help uninsured or out-of-network patients budget medical costs","To guarantee free medications","To provide hospital admission privileges"],correct:1,explanation:"The membership option can help uninsured or out-of-network patients make their healthcare costs more predictable."}
];
export const QUESTION_BY_ID=Object.fromEntries(QUESTION_BANK.map(q=>[q.id,q]));
export function chooseQuestionIds(count){const shuffled=[...QUESTION_BANK];for(let i=shuffled.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]]}return shuffled.slice(0,Math.min(count,shuffled.length)).map(q=>q.id)}
